import api from './client'

export const listGames       = ()        => api.get('/games').then(r => r.data.games)
export const getGame         = id        => api.get(`/games/${id}`).then(r => r.data.game)
export const createGame      = data      => api.post('/games', data).then(r => r.data)
export const updateGame      = (id, data)=> api.put(`/games/${id}`, data).then(r => r.data)
export const activateGame    = id        => api.post(`/games/${id}/activate`).then(r => r.data)
export const closeGame       = id        => api.post(`/games/${id}/close`).then(r => r.data)
export const reopenGame      = id        => api.post(`/games/${id}/reopen`).then(r => r.data)
export const resolveGame     = (id, data)=> api.post(`/games/${id}/resolve`, data).then(r => r.data)
export const deleteGame      = id        => api.post(`/games/${id}/delete`).then(r => r.data)
export const submitEntry     = (id, data)=> api.post(`/games/${id}/enter`, data).then(r => r.data)
export const getPortfolio    = id        => api.get(`/games/${id}/portfolio`).then(r => r.data)
export const submitVirtualTrade = (id, data) => api.post(`/games/${id}/trade`, data).then(r => r.data)
export const getCredits            = ()       => api.get('/credits').then(r => r.data)
export const getPlans              = ()       => api.get('/plans').then(r => r.data.plans)
export const subscribeWithCredits  = plan_id  => api.post('/subscribe-with-credits', { plan_id }).then(r => r.data)
