import api from './client'

export const listRecs           = ()               => api.get('/recommendations').then(r => r.data.recommendations)
export const fetchPrices        = (keys)           => api.post('/prices', { keys }).then(r => r.data)
export const createRec          = data              => api.post('/recommendations/create', data).then(r => r.data)
export const deleteRec          = id               => api.post(`/recommendations/${id}/delete`).then(r => r.data)
export const exitRec            = (id, data)       => api.post(`/recommendations/${id}/exit`, data).then(r => r.data)
export const adjustRec          = (id, data)       => api.post(`/recommendations/${id}/adjust`, data).then(r => r.data)
export const createAccountTrade = data             => api.post('/account-trades/create', data).then(r => r.data)
export const listTrades         = params           => api.get('/account-trades', { params }).then(r => r.data.trades)
export const listHistory        = params           => api.get('/account-trades/history', { params }).then(r => r.data.trades)
export const exitTrade          = (id, data)       => api.post(`/account-trades/${id}/exit`, data).then(r => r.data)
export const applyAdjTrade      = (id, data)       => api.post(`/account-trades/${id}/adjust`, data).then(r => r.data)
export const deleteTrade        = id               => api.post(`/account-trades/${id}/delete`).then(r => r.data)
export const listBrokers        = ()               => api.get('/brokers').then(r => r.data.brokers)
export const addBroker          = data             => api.post('/brokers', data).then(r => r.data)
export const listAccounts       = ()               => api.get('/accounts').then(r => r.data.accounts)
export const addAccount         = data             => api.post('/accounts', data).then(r => r.data)
export const searchInstruments  = q               => api.get(`/search?q=${encodeURIComponent(q)}`).then(r => r.data.results)
